version: '3.8'
services:
  mvc:
    build: .
    image: mvcmovie:latest
    ports:
      - "5030:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ProductionMvcMovieContext=Data Source=/data/MvcMovie.db
    volumes:
      - ./data:/data